### ISSUE TITLE
License Inconsistent with Language in 'README.md'

### ISSUE THREAD

**Issue by Librechain** [GeoSn0w/iSecureOS#17]
At the bottom of your ```README.md``` for this repo, you state the following (under a heading titled, 'License particularities'):

> "*WE STRICTLY DISALLOW CLONES WITH MODIFIED UI AND BASICALLY NO FEATURES ADDED, OR MINOR FEATURES. If your fork is a reskin and it does not contribute in any way to the iSecureOS project with features, improvements or any other user beneficial changes, it might be taken down.*" 

> "*In other words, if you intend to change the name of the app and the logo and slap your name in the credits, it won't cut it. If you wanna actually help with the project, open a pull request. Spawning clones of the app with different names won't help the project.*" 

However, your project is licensed under GPLv2 here: https://github.com/GeoSn0w/iSecureOS/blob/main/LICENSE (which you specified for GitHub when you uploaded this project to begin with). Normally I wouldn't make an 'issue' out of this ("issue" referring to the feature on GitHub), but since you implicitly threatened some sort of retaliatory action for any and all individuals that choose to create "clones" with "modified UI and basically no features added", I felt compelled to point out that the actual license that you attached to this project (*which supersedes what you wrote in the* ```readme.md```) states **the exact opposite**. 

In fact, out of all open source licenses that you could've chose to attach to this project, you may have very well selected **the most permissive open-source license in existence**. I'm going to assume that you didn't know this and simply made a mistake, but I wanted to point this out to you because the reasons and motivations behind this license's permissive nature are iterated explicitly in the text of the license itself. 

I'll highlight some of these tenets for you below (quoted directly): 

- "*The licenses for most software are designed to take away your
freedom to share and change it.  By contrast, the GNU General Public
License is intended to guarantee your freedom to share and change free
software--to make sure the software is free for all its users.*"

- "*Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
this service if you wish), that you receive source code or can get it
if you want it, that you can change the software or use pieces of it
in new free programs; and that you know you can do these things.*"

- "*To protect your rights, we need to make restrictions that forbid
anyone to deny you these rights or to ask you to surrender the rights.
These restrictions translate to certain responsibilities for you if you
distribute copies of the software, or if you modify it.*" 

- "*If you distribute copies of such a program, whether
gratis or for a fee, you must give the recipients all the rights that
you have.  You must make sure that they, too, receive or can get the
source code.  And you must show them these terms so they know their
rights.*"

- "*We protect your rights with two steps: (1) copyright the software, and
(2) offer you this license which gives you legal permission to copy,
distribute and/or modify the software.*" 

> **edit**: *Wanted to mention that the use of the pronoun* "**you**" *refers to the prospective user / downloader of the project that has this license attached...not the developer attaching this license to their project (at the time someone is reading that license*). 

As you likely deduced from the quotes above, the license that you attached to this project was actually designed to **prevent people from carrying out the threat you included at the bottom of your** ```readme.md``` (*and from making the threat at all, though this latter bit is more implicit since there's no facet of the license that prohibits one from making threats within the txt / documentation of their project that are wholly inconsistent with the permissions granted in the license attached to that very same project - guess they didn't anticipate that*!).

To be clear, I have **no opinion** either way about this. There is plenty of proprietary software out there that people use on a regular basis. Your repo helps people secure jailbroken iPhones, so anyone that's using this repo must be an individual that's comfortable with proprietary software on some level (or they wouldn't have purchased an iPhone to begin with). However, in your case, you've undermined yourself by attaching the GPLv2 license to this project (maybe). 

I think you should look a bit more into the philosophy and ethos behind the FSF and explore what went into the crafting of the GPL licenses (as well as the 'MIT License'). Doing so may ultimately change your opinion about those simply "copying" and deploying the source code for your application. In my experience, I find that its **exceedingly rare** for someone to copy/paste another developer's project (line for line), re-deploy it under their branding & gather **more** traction / success / attention than the original. With that being said, I'm sure there are examples of this that I simply have not yet come across. 

In either case, one must ask themselves, 'Is this a bad thing if I'm already giving away the software for others to use for free?'. Also, 'Would I have ever been able to develop this open source project and publish it if it weren't for the contributions of other giants in the computer space that open sourced various libraries, packages, software etc., in the years & decades prior to the publishing of this specific app?'. I'm not sure what answer you'll come to for those questions (or if you'll even ask them). 

### Wrap-Up / Conclusion 

I've rambled enough. If nothing else, I created this issue to make you aware that publishing the source code for this repo w the GPLv2 license has effectively eliminated any grounds or argument you'd have for having a "clone" project taken down unless you find that said clone has omitted this GPLv2 license. 

Don't get bummed out about it though! I think you'll be fine regardless. You've had the GPLv2 license on this project this entire time (at least a few months), and I assume no one has cloned your project. You are seen as the de facto official maintainer & I highly doubt anyone would download a repo (especially one of this nature), from any source other than the "original". 

Have faith in your abilities as a developer as well as your promotional efforts! You've done a great job increasing awareness about this tool and I'm sure you have many downloads / users at this point. Those people inherently trust you in some regards. I highly doubt that anyone attempting to clone this project and publish it (for w/e reason), would ever get traction / clout from **anyone** and they certainly would have 0 success luring users away from what you've built.

**Comment by GeoSn0w** [comment]
Thank you for your issue and for the time you spend documenting it.

Unfortunately, clones of popular jailbreak apps with just the name and logo changed have happened before in the jailbreak community. They've even made it to the AppStore as paid apps while the real app is free and open-source.

However, you are right. I do not care enough about this to essentially break GPL over it. As such, I've removed the license limitations making it essentially GPLv2.

Have a great day!
