### ISSUE TITLE
SSH threat detection

### ISSUE THREAD

**Issue by PaulProjects** [GeoSn0w/iSecureOS#7]
I noticed that the ISecureOS App shows you the same "Urgent Threat has been detected!" screen all the time:
![32E2B234-C6ED-45BC-9E78-9964C3E134BF](https://user-images.githubusercontent.com/77199889/113253956-42649500-92c6-11eb-888d-c97beb2fddff.png)
The text says two things:
1. Someone **attempts** to connect to your device via SSH
2. This someone does that as ROOT

When I got this screen I was
1. already loged in (in this case with an SSH key, but it also works with the password)
2. loged in as mobile
I think the "real" effect is just in 1., as users could believe that they closely passed a hacking attempt, but meanwhile the hacker could already access the whole device.

**Comment by GeoSn0w** [comment]
There are two screens with different text for attempts and successful intrusions. For some reason the app defaults to one. Will fix.

**Comment by milkly1235writer** [comment]
Use
